In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Caso 1.csv")

In [4]:
a = 'Churn'

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df = df.drop('customerID', 1)
df = df.drop('Dependents', 1)

In [6]:
df['tenure'] = df['tenure'].replace([0, 1, 2, 3, 4, 5], "Entre 0 y 5")
df['tenure'] = df['tenure'].replace([6, 7, 8, 9, 10, 11], "Entre 6 y 11")
df['tenure'] = df['tenure'].replace([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23], "Entre 12 y 23")
df['tenure'] = df['tenure'].replace([24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35], "Entre 24 y 35")
df['tenure'] = df['tenure'].replace([36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73], "Mas de 35")

df.head()

,gender,SeniorCitizen,Partner,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,Entre 0 y 5,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,Entre 24 y 35,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,Entre 0 y 5,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,Mas de 35,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,Entre 0 y 5,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [7]:
def getRange(x):
    if x['MonthlyCharges'] < 26:
        return "Menos de 26"
    elif 26 <= x['MonthlyCharges'] < 50:
        return "Entre 26 y 50"
    elif 50 <= x['MonthlyCharges'] < 76:
        return "Entre 50 y 76"
    return "Mas de 77"

In [8]:
# Se pasan los cargos mensuales a rango

df['CargosMensuales'] = df.apply(lambda row: getRange(row),axis=1)

In [9]:
df.head()

,gender,SeniorCitizen,Partner,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CargosMensuales
0,Female,0,Yes,Entre 0 y 5,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,Entre 26 y 50
1,Male,0,No,Entre 24 y 35,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No,Entre 50 y 76
2,Male,0,No,Entre 0 y 5,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,Entre 50 y 76
3,Male,0,No,Mas de 35,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,Entre 26 y 50
4,Female,0,No,Entre 0 y 5,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,Entre 50 y 76

In [12]:
# Esto se ejecuta una vez
import psycopg2
conn = psycopg2.connect(host="localhost",database="proyecto_bi", user="proyecto_bi", password="123456")
cur = conn.cursor()

In [17]:
print('PostgreSQL database version:')
cur.execute('SELECT version()')
 
# display the PostgreSQL database server version
db_version = cur.fetchone()
print(db_version)

PostgreSQL database version:

InterfaceError: cursor already closed

In [15]:
cur.close()